from pathlib import Path
p=Path("LiveContainerSwiftUI/Utilities/LCUtils.m");s=p.read_text();m="@import Security;\n"
h="""#include <mach-o/dyld.h>\n#include <servers/bootstrap.h>\n#include <objc/runtime.h>\n#include <sandbox.h>\n"""
if m not in s:raise SystemExit("import marker missing")
if "servers/bootstrap.h" not in s:s=s.replace(m,m+h,1)
i="@implementation LCUtils\n"
c=r'''
extern void *SecTaskCreateFromSelf(CFAllocatorRef);
extern CFTypeRef SecTaskCopyValueForEntitlement(void *, CFStringRef, CFErrorRef *);
static BOOL FlekPVMatch(const char*r){if(!r)return NO;NSString*v=[[NSString stringWithUTF8String:r]lowercaseString];return[v containsString:@"preview"]||[v containsString:@"xojit"]||[v containsString:@"appmanager"]||[v containsString:@"grantexecute"]||[v containsString:@"copyurl"]||[v containsString:@"agentdescriptor"]||[v containsString:@"jitload"];}
static NSArray<NSString*>*FlekRunPreviewXOJITProbe(NSString*source){NSMutableArray*o=[NSMutableArray arrayWithObject:@"FlekDeck Preview/XOJIT Probe"];void*t=SecTaskCreateFromSelf(NULL);for(NSString*k in @[@"get-task-allow",@"com.apple.private.oop-jit.loader",@"com.apple.private.oop-jit.runner",@"com.apple.developer.swift-playgrounds-app.development-build",@"com.apple.private.amfi.can-execute-cdhash"]){CFErrorRef e=NULL;CFTypeRef v=t?SecTaskCopyValueForEntitlement(t,(__bridge CFStringRef)k,&e):NULL;[o addObject:[NSString stringWithFormat:@"host %@=%@",k,v?(__bridge id)v:@"<missing>"]];if(v)CFRelease(v);if(e)CFRelease(e);}if(t)CFRelease((CFTypeRef)t);
NSArray*fs=@[@"/System/Library/PrivateFrameworks/PreviewsMessagingOS.framework/PreviewsMessagingOS",@"/System/Library/PrivateFrameworks/PreviewsOSSupport.framework/PreviewsOSSupport",@"/System/Library/PrivateFrameworks/PreviewsInjection.framework/PreviewsInjection"];for(NSString*f in fs){struct stat st;errno=0;int sr=lstat(f.fileSystemRepresentation,&st),se=sr?errno:0;dlerror();void*h=dlopen(f.fileSystemRepresentation,RTLD_LAZY|RTLD_LOCAL);const char*de=dlerror();[o addObject:[NSString stringWithFormat:@"framework %@ exists=%@ stat=%d/%d dlopen=%@ error=%s",f.lastPathComponent,sr?@"NO":@"YES",sr,se,h?@"PASS":@"FAIL",de?:"<none>"]];}
NSMutableOrderedSet*rt=[NSMutableOrderedSet orderedSet];int n=objc_getClassList(NULL,0);Class*cs=n>0&&n<100000?calloc(n,sizeof(Class)):NULL;if(cs){n=objc_getClassList(cs,n);for(int z=0;z<n&&rt.count<128;z++)if(FlekPVMatch(class_getName(cs[z])))[rt addObject:[NSString stringWithFormat:@"class %s",class_getName(cs[z])]];free(cs);}unsigned int pc=0;Protocol*__unsafe_unretained*ps=objc_copyProtocolList(&pc);for(unsigned z=0;ps&&z<pc&&rt.count<128;z++)if(FlekPVMatch(protocol_getName(ps[z])))[rt addObject:[NSString stringWithFormat:@"protocol %s",protocol_getName(ps[z])]];free(ps);[o addObject:[NSString stringWithFormat:@"runtime registrations=%lu",(unsigned long)rt.count]];for(NSString*v in rt)[o addObject:[@"runtime " stringByAppendingString:v]];
NSArray*candidates=@[@"com.apple.previewsd",@"com.apple.previewservice",@"com.apple.PreviewShell",@"com.apple.XOJIT"];BOOL reach=NO;for(NSString*v in candidates){BOOL evidence=NO;for(NSString*r in rt)if([[r lowercaseString]containsString:v.lowercaseString]){evidence=YES;break;}if(!evidence){[o addObject:[NSString stringWithFormat:@"preview transport service=%@ lookup=SKIPPED reason=no runtime evidence",v]];continue;}int sb=sandbox_check(getpid(),"mach-lookup",SANDBOX_FILTER_GLOBAL_NAME,v.UTF8String);mach_port_t port=MACH_PORT_NULL;kern_return_t kr=bootstrap_look_up(bootstrap_port,v.UTF8String,&port);if(kr==KERN_SUCCESS&&MACH_PORT_VALID(port)){reach=YES;mach_port_deallocate(mach_task_self(),port);}[o addObject:[NSString stringWithFormat:@"preview transport service=%@ sandbox=%d lookup=%d connection=%@",v,sb,kr,kr==KERN_SUCCESS?@"PORT ACQUIRED":@"DENIED/UNAVAILABLE"]];}
NSString*j=[[rt array]componentsJoinedByString:@"\n"].lowercaseString;BOOL am=[j containsString:@"appmanager"],cp=[j containsString:@"copyurl"],gr=[j containsString:@"grantexecute"],ad=[j containsString:@"agentdescriptor"];[o addObject:[NSString stringWithFormat:@"AppManager available=%@ activated=%@",am?@"YES":@"NO",am&&reach?@"TRANSPORT REACHABLE":@"NO"]];[o addObject:[NSString stringWithFormat:@"CopyURL request=%@ response=NOT SENT finalPath=<none> error=%@",cp?@"TYPE DISCOVERED":@"TYPE MISSING",reach?@"safe Swift ABI unavailable":@"transport unavailable"]];[o addObject:[NSString stringWithFormat:@"GrantExecutePermission request=%@ response=NOT SENT error=%@ agentDescriptor=%@",gr?@"TYPE DISCOVERED":@"TYPE MISSING",reach?@"safe Swift ABI unavailable":@"transport unavailable",ad?@"DISCOVERED":@"MISSING"]];[o addObject:[NSString stringWithFormat:@"post-grant targetPath=%@ mmap=SKIPPED dlopen=SKIPPED constructor=SKIPPED reason=no successful grant",source]];[o addObject:@"guest attempted=NO result=probe only; existing fallback preserved"];return o;}
'''
if i not in s:raise SystemExit("implementation marker missing")
if "FlekRunPreviewXOJITProbe" not in s:s=s.replace(i,c+i,1)
r="        NSMutableArray<NSString *> *report = [NSMutableArray array];\n"
if r not in s:raise SystemExit("report marker missing")
if "addObjectsFromArray:FlekRunPreviewXOJITProbe" not in s:s=s.replace(r,r+"        [report addObjectsFromArray:FlekRunPreviewXOJITProbe(tmpLibPath)];\n",1)
p.write_text(s)
