from pathlib import Path
p=Path("LiveContainerSwiftUI/Utilities/LCUtils.m");s=p.read_text();m="@import Security;\n"
h="""#include <mach-o/dyld.h>\n#include <mach-o/loader.h>\n#include <mach/mach.h>\n#include <objc/runtime.h>\n"""
if m not in s:raise SystemExit("import marker missing")
if "extern mach_port_t bootstrap_port" not in s:s=s.replace(m,m+h,1)
i="@implementation LCUtils\n"
c=r'''
extern mach_port_t bootstrap_port;
extern kern_return_t bootstrap_look_up(mach_port_t, const char *, mach_port_t *);
extern int sandbox_check(pid_t, const char *, int, ...);
#define FLEK_SANDBOX_FILTER_GLOBAL_NAME 2
extern void *SecTaskCreateFromSelf(CFAllocatorRef);
extern CFTypeRef SecTaskCopyValueForEntitlement(void *, CFStringRef, CFErrorRef *);
static BOOL FlekPVMatch(const char*r){if(!r)return NO;NSString*v=[[NSString stringWithUTF8String:r]lowercaseString];return[v containsString:@"preview"]||[v containsString:@"xojit"]||[v containsString:@"appmanager"]||[v containsString:@"grantexecute"]||[v containsString:@"copyurl"]||[v containsString:@"agentdescriptor"]||[v containsString:@"jitload"];}
static BOOL FlekPVRuntime(const char*r){if(!r)return NO;NSString*v=[NSString stringWithUTF8String:r];return[v containsString:@"PreviewsMessagingOS"]||[v containsString:@"PreviewsOSSupport"]||[v containsString:@"PreviewsInjection"]||[v containsString:@"PreviewsServices"]||[v containsString:@"XOJITExecutor"];}
static void FlekPVScanBytes(const uint8_t*b,uint64_t size,NSMutableOrderedSet*meta,NSMutableOrderedSet*services){if(!b||!size||size>(128ULL<<20))return;for(uint64_t i=0;i<size;){while(i<size&&(b[i]<32||b[i]>126))i++;uint64_t start=i;while(i<size&&b[i]>=32&&b[i]<=126)i++;uint64_t len=i-start;if(len<4||len>2048)continue;char tmp[2049];memcpy(tmp,b+start,(size_t)len);tmp[len]=0;if(!FlekPVMatch(tmp))continue;NSString*v=[NSString stringWithUTF8String:tmp];if(v.length&&meta.count<256)[meta addObject:v];NSString*l=v.lowercaseString;if([v hasPrefix:@"com.apple."]&&([l containsString:@"preview"]||[l containsString:@"xojit"])&&[v rangeOfCharacterFromSet:[[NSCharacterSet characterSetWithCharactersInString:@"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_"] invertedSet]].location==NSNotFound&&services.count<32)[services addObject:v];}}
static void FlekPVScanImage(const struct mach_header_64*h,intptr_t slide,NSMutableOrderedSet*meta,NSMutableOrderedSet*services){if(!h||h->magic!=MH_MAGIC_64||h->sizeofcmds>(32U<<20))return;const uint8_t*base=(const uint8_t*)(h+1),*end=base+h->sizeofcmds;const struct load_command*lc=(const void*)base;for(uint32_t i=0;i<h->ncmds;i++){const uint8_t*q=(const void*)lc;if(q<base||q+sizeof(*lc)>end||lc->cmdsize<sizeof(*lc)||q+lc->cmdsize>end)return;if(lc->cmd==LC_SEGMENT_64&&lc->cmdsize>=sizeof(struct segment_command_64)){const struct segment_command_64*g=(const void*)lc;const struct section_64*x=(const void*)(g+1);uint32_t count=MIN(g->nsects,(uint32_t)((lc->cmdsize-sizeof(*g))/sizeof(*x)));for(uint32_t j=0;j<count;j++){BOOL wanted=!strncmp(x[j].sectname,"__cstring",16)||!strncmp(x[j].sectname,"__swift5_reflstr",16)||!strncmp(x[j].sectname,"__swift5_typeref",16);if(wanted)FlekPVScanBytes((const uint8_t*)(uintptr_t)(x[j].addr+slide),x[j].size,meta,services);}}lc=(const void*)(q+lc->cmdsize);}}
static NSArray<NSString*>*FlekRunPreviewXOJITProbe(NSString*source){NSMutableArray*o=[NSMutableArray arrayWithObject:@"FlekDeck Preview/XOJIT Probe"];void*t=SecTaskCreateFromSelf(NULL);for(NSString*k in @[@"get-task-allow",@"com.apple.private.oop-jit.loader",@"com.apple.private.oop-jit.runner",@"com.apple.developer.swift-playgrounds-app.development-build",@"com.apple.private.amfi.can-execute-cdhash"]){CFErrorRef e=NULL;CFTypeRef v=t?SecTaskCopyValueForEntitlement(t,(__bridge CFStringRef)k,&e):NULL;[o addObject:[NSString stringWithFormat:@"host %@=%@",k,v?(__bridge id)v:@"<missing>"]];if(v)CFRelease(v);if(e)CFRelease(e);}if(t)CFRelease((CFTypeRef)t);
NSArray*fs=@[@"/System/Library/PrivateFrameworks/PreviewsMessagingOS.framework/PreviewsMessagingOS",@"/System/Library/PrivateFrameworks/PreviewsOSSupport.framework/PreviewsOSSupport",@"/System/Library/PrivateFrameworks/PreviewsInjection.framework/PreviewsInjection"];NSMutableSet*loaded=[NSMutableSet set];for(NSString*f in fs){struct stat st;errno=0;int sr=lstat(f.fileSystemRepresentation,&st),se=sr?errno:0;dlerror();void*h=dlopen(f.fileSystemRepresentation,RTLD_LAZY|RTLD_LOCAL);const char*de=dlerror();[o addObject:[NSString stringWithFormat:@"framework %@ exists=%@ stat=%d/%d dlopen=%@ error=%s",f.lastPathComponent,sr?@"NO":@"YES",sr,se,h?@"PASS":@"FAIL",de?:"<none>"]];if(h)[loaded addObject:f];}
NSMutableOrderedSet*rt=[NSMutableOrderedSet orderedSet];int n=objc_getClassList(NULL,0);Class*cs=n>0&&n<100000?(__unsafe_unretained Class*)calloc(n,sizeof(Class)):NULL;if(cs){n=objc_getClassList(cs,n);for(int z=0;z<n&&rt.count<128;z++)if(FlekPVRuntime(class_getName(cs[z])))[rt addObject:[NSString stringWithFormat:@"class %s",class_getName(cs[z])]];free(cs);}unsigned int pc=0;Protocol*__unsafe_unretained*ps=objc_copyProtocolList(&pc);for(unsigned z=0;ps&&z<pc&&rt.count<128;z++)if(FlekPVRuntime(protocol_getName(ps[z])))[rt addObject:[NSString stringWithFormat:@"protocol %s",protocol_getName(ps[z])]];free(ps);[o addObject:[NSString stringWithFormat:@"runtime registrations=%lu",(unsigned long)rt.count]];for(NSString*v in rt)[o addObject:[@"runtime " stringByAppendingString:v]];
NSMutableOrderedSet*meta=[NSMutableOrderedSet orderedSet],*services=[NSMutableOrderedSet orderedSet];for(uint32_t z=0;z<_dyld_image_count();z++){const char*raw=_dyld_get_image_name(z);if(!raw)continue;NSString*name=[NSString stringWithUTF8String:raw];BOOL relevant=NO;for(NSString*f in loaded)if([name isEqualToString:f]||[name.lastPathComponent isEqualToString:f.lastPathComponent]){relevant=YES;break;}if(relevant){[o addObject:[NSString stringWithFormat:@"framework image=%@",name]];FlekPVScanImage((const struct mach_header_64*)_dyld_get_image_header(z),_dyld_get_image_vmaddr_slide(z),meta,services);}}[o addObject:[NSString stringWithFormat:@"framework metadata=%lu services=%lu",(unsigned long)meta.count,(unsigned long)services.count]];for(NSString*v in meta)[o addObject:[@"metadata " stringByAppendingString:v]];BOOL reach=NO;for(NSString*v in services){int sb=sandbox_check(getpid(),"mach-lookup",FLEK_SANDBOX_FILTER_GLOBAL_NAME,v.UTF8String);mach_port_t port=MACH_PORT_NULL;kern_return_t kr=bootstrap_look_up(bootstrap_port,v.UTF8String,&port);if(kr==KERN_SUCCESS&&MACH_PORT_VALID(port)){reach=YES;mach_port_deallocate(mach_task_self(),port);}[o addObject:[NSString stringWithFormat:@"preview transport service=%@ sandbox=%d lookup=%d connection=%@",v,sb,kr,kr==KERN_SUCCESS?@"PORT ACQUIRED":@"DENIED/UNAVAILABLE"]];}if(!services.count)[o addObject:@"preview transport service=<none discovered> connection=NOT ATTEMPTED"];
NSString*j=[NSString stringWithFormat:@"%@\n%@",[[rt array]componentsJoinedByString:@"\n"],[[meta array]componentsJoinedByString:@"\n"]].lowercaseString;BOOL am=[j containsString:@"appmanager"],cp=[j containsString:@"copyurl"],gr=[j containsString:@"grantexecute"],ad=[j containsString:@"agentdescriptor"];[o addObject:[NSString stringWithFormat:@"AppManager available=%@ activated=%@",am?@"YES":@"NO",am&&reach?@"TRANSPORT REACHABLE":@"NO"]];[o addObject:[NSString stringWithFormat:@"CopyURL request=%@ response=NOT SENT finalPath=<none> error=%@",cp?@"TYPE DISCOVERED":@"TYPE MISSING",reach?@"safe Swift ABI unavailable":@"transport unavailable"]];[o addObject:[NSString stringWithFormat:@"GrantExecutePermission request=%@ response=NOT SENT error=%@ agentDescriptor=%@",gr?@"TYPE DISCOVERED":@"TYPE MISSING",reach?@"safe Swift ABI unavailable":@"transport unavailable",ad?@"DISCOVERED":@"MISSING"]];[o addObject:[NSString stringWithFormat:@"post-grant targetPath=%@ mmap=SKIPPED dlopen=SKIPPED constructor=SKIPPED reason=no successful grant",source]];[o addObject:@"guest attempted=NO result=probe only; existing fallback preserved"];return o;}
'''
if i not in s:raise SystemExit("implementation marker missing")
if "FlekRunPreviewXOJITProbe" not in s:s=s.replace(i,c+i,1)
r="        NSMutableArray<NSString *> *report = [NSMutableArray array];\n"
if r not in s:raise SystemExit("report marker missing")
if "addObjectsFromArray:FlekRunPreviewXOJITProbe" not in s:s=s.replace(r,r+"        [report addObjectsFromArray:FlekRunPreviewXOJITProbe(tmpLibPath)];\n",1)
p.write_text(s)
