name: FlekDeck 32-bit Temp IPA

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  canonical-sidestore-build:
    uses: ./.github/workflows/build-flekdeck-sidestore-parity-temp.yml
    secrets: inherit
